---
title: "daily"
author: "Hannah Reich"
date: "6/21/2021"
output: html_document
---

# 20210621, SCRIPT adapted FROM Jill https://github.com/JillAshey/Astrangia_repo/blob/main/scripts/Daily.Rmd 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}
library(tidyverse)
library(gridExtra)
library(dplyr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(ggpubr)
```

# Check working directory
```{r}
setwd("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_Resourses/CBLS_Aquarium_WQ_Tracking") #didn't work for some reason, couldn't change from tris_cal folder
getwd() 
```

# Load data
```{r}
# Load data
daily <- read.csv("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_Resourses/CBLS_Aquarium_WQ_Tracking/CBLS_watertables_waterquality_tracking.csv", header = T)
#daily$Timepoint <- as.Date(daily$Timepoint, "%m/%d/%Y")
daily$Tank_ID <- as.factor(daily$Tank_ID)
daily$Treatment_ID <- as.factor(daily$Treatment_ID)
```

# Discrete pH calculations from Tris calibrations.
```{r}
path <-("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_Resourses/CBLS_Aquarium_WQ_Tracking/tris_cal") #set path to calibration files
file.names<-list.files(path = path, pattern = "csv$") #list all the file names in the folder to get only get the csv files
pH.cals <- data.frame(matrix(NA, nrow=length(file.names), ncol=3, dimnames=list(file.names,c("Date", "Intercept", "Slope")))) #generate a 3 column dataframe with specific column names
for(i in 1:length(file.names)) { # for every file in list start at the first and run this following function
  Calib.Data <-read.table(file.path(path,file.names[i]), header=TRUE, sep=",", na.string="NA", as.is=TRUE) #reads in the data files
  file.names[i]
  model <-lm(mVTris ~ TTris, data=Calib.Data) #runs a linear regression of mV as a function of temperature
  coe <- coef(model) #extracts the coeffecients
  summary(model)$r.squared #extracts the r squared
  plot(Calib.Data$mVTris, Calib.Data$TTris) #plots the regression data
  pH.cals[i,2:3] <- coe #inserts coefficients in the dataframe
  pH.cals[i,1] <- substr(file.names[i],1,8) #stores the file name in the Date column
}
colnames(pH.cals) <- c("Calib.Date",  "Intercept",  "Slope") #rename columns
pH.cals #view data
#constants for use in pH calculation 
R <- 8.31447215 #gas constant in J mol-1 K-1 
F <- 96485.339924 #Faraday constant in coulombs mol-1
#merge with Seawater chemistry file (in our case, the WQ file!)
SW.chem <- merge(daily, pH.cals, by.x="Date", by.y="Calib.Date", all=TRUE)
```

# Calculate total pH. 
```{r}
mvTris <- SW.chem$Temperature_C*SW.chem$Slope+SW.chem$Intercept #calculate the mV of the tris standard using the temperature mV relationships in the measured standard curves 
STris<-35 #salinity of the Tris
phTris<- (11911.08-18.2499*STris-0.039336*STris^2)*(1/(SW.chem$Temperature_C+273.15))-366.27059+ 0.53993607*STris+0.00016329*STris^2+(64.52243-0.084041*STris)*log(SW.chem$Temperature_C+273.15)-0.11149858*(SW.chem$Temperature_C+273.15) #calculate the pH of the tris (Dickson A. G., Sabine C. L. and Christian J. R., SOP 6a)

SW.chem$pH.Total<-phTris+((mvTris/1000)-(SW.chem$pH_mv/1000))/(R*(SW.chem$Temperature_C+273.15)*(log(10)/F)) #calculate the pH on the total scale (Dickson A. G., Sabine C. L. and Christian J. R., SOP 6a)

write.csv(SW.chem,file="/Users/roxyr/Documents/GitHub/Lab_Management/Lab_Resourses/CBLS_Aquarium_WQ_Tracking/WQ_with_total_pH")

# SAVE SW CHEM FILE (HAS TOTAL PH)
```

# load data
```{r}
SW.chem$Date <- as.factor(SW.chem$Date)
# filter out the water tables
wt <- dplyr::filter(SW.chem, Treatment_ID == c("WaterTables"))

# plot temp
temp_wt <- ggplot(data=wt, aes(x=Date, y=Temperature_C, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=Temperature_C)) +
  theme_bw() +
  scale_color_gradient(low = "blue", high = "red") +
  labs(title = "Water Tables Temperature (C)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
temp_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_TEMP.png", temp_wt, base_aspect_ratio = 1.8)

# plot salinity
sal_wt <- ggplot(data=wt, aes(x=Date, y=Salinity_psu, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=Salinity_psu)) +
  theme_bw() +
  scale_color_gradient(low = "yellow", high = "lime green") +
  labs(title = "Water Tables Salinity (psu)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
sal_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_SALINITY.png", sal_wt, base_aspect_ratio = 1.8)

# plot pH

# average pH between the 2 water tables
# wtphavg <- wt %>% group_by(Date) %>% summarise(pH_mv_avg = mean(pH_mv, na.rm = TRUE))

ph_wt <- ggplot(data=wt, aes(x=Date, y=pH.Total, group = 1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=pH.Total)) +
  theme_bw() +
  scale_color_gradient(low = "purple", high = "cyan") +
  labs(title = "Water Tables pH (mv)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
ph_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_pH_MV.png", ph_wt, base_aspect_ratio = 1.8)
```
```{r}
# plot light
light_wt <- ggplot(data=wt, aes(x=Date, y=Light, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=Light)) +
  theme_bw() +
  scale_color_gradient(low ="grey", high = "blue") +
  labs(title = "Water Tables Light (umol/m^2/S)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
light_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_light.png", light_wt, base_aspect_ratio = 1.8)


# plot Ca+
Ca_wt <- ggplot(data=wt, aes(x=Date, y=Ca_ppm, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=Ca_ppm)) +
  theme_bw() +
  scale_color_gradient(low = "black", high = "grey") +
  labs(title = "Water Tables Ca+ (ppm Mg/L)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
Ca_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_Calcium.png", Ca_wt, base_aspect_ratio = 1.8)

# plot KH
KH_wt <- ggplot(data=wt, aes(x=Date, y=KH_ppm, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=KH_ppm)) +
  theme_bw() +
  scale_color_gradient(low = "blue", high = "yellow") +
  labs(title = "Water Tables KH (ppm KH)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
KH_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_KH.png", KH_wt, base_aspect_ratio = 1.8)


# plot PO4
PO4_wt <- ggplot(data=wt, aes(x=Date, y=PO4_ppm, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=PO4_ppm)) +
  theme_bw() +
  scale_color_gradient(low = "yellow", high = "blue") +
  labs(title = "Water Tables PO4(Mg/L ppm)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
PO4_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_PO4.png", PO4_wt, base_aspect_ratio = 1.8)


# plot NH4
NH4_wt <- ggplot(data=wt, aes(x=Date, y=NH4_ppm, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=NH4_ppm)) +
  theme_bw() +
  scale_color_gradient(low = "red", high = "yellow") +
  labs(title = "Water Tables NH4 (ppm)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
NH4_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_NH4.png", NH4_wt, base_aspect_ratio = 1.8)


# plot NO3
NO3_wt <- ggplot(data=wt, aes(x=Date, y=NO3_ppm, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=NO3_ppm)) +
  theme_bw() +
  scale_color_gradient(low = "purple", high = "blue") +
  labs(title = "Water Tables NO3 (ppm)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
NO3_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_NO3.png", NO3_wt, base_aspect_ratio = 1.8)


# plot NO2
NO2_wt <- ggplot(data=wt, aes(x=Date, y=NO2_ppm, group=1)) +
  geom_line(colour = "gray70")+
  geom_point(size = 3, aes(color=NO2_ppm)) +
  theme_bw() +
  scale_color_gradient(low = "blue", high = "green") +
  labs(title = "Water Tables NO2 (ppm)") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, size = 6, vjust = 1, hjust = 1),
        legend.position = "bottom")
NO2_wt

save_plot("/Users/roxyr/Documents/GitHub/Lab_Management/Lab_resourses/CBLS_Aquarium_WQ_tracking/Water_Quality_figures/Water_Tables_NO2.png", NO2_wt, base_aspect_ratio = 1.8)
```





