---
title: "CBLSWaterTables_WQ_Tracking"
author: "Danielle Becker-Polinski"
date: '20220120'
output:
  pdf_document: default
  html_document: default
---


# Set Up    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```
 
 
#Load libraries and data files 
```{r}
# load packages
library(ggplot2)
library(cowplot)
library(dplyr)
library(reshape2)
library(ggpubr)
library(lubridate)
library(here)

here

# load data
dat <- read.csv("../data/CBLS_watertables_waterquality_tracking.csv")

dat$date <- as.factor(dat$date)

#format date using lubridate package
dat$date  <- mdy(dat$date) 


```


#Summarize
```{r}
#temp data across date summarized
dat.grouped <-dat %>%
  group_by(date, tank, WQ.type) %>% #tells to group by treatment
  summarise(mean=mean(measurement), se=sd(measurement)/sqrt(n())) #calculates mean and se
dat.grouped
```

#Temperature plot
```{r}

#filter for just temp data

temp.dat <- filter(dat.grouped, WQ.type == "temp")


#plot mean temp per day by date
temp_plot <- temp.dat %>%
  ggplot(aes(x=date, y=mean, color = tank))+
  geom_line() + 
  geom_point() +
  scale_x_date(date_breaks = "1 day", date_labels = "%m-%d") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90)) +
  ylab("Temperature (°C)")+
  xlab("Date");temp_plot

ggsave(filename="../figures/temperature.plot.pdf", plot=temp_plot, width=10, height=5, units="in")

```


#Salinity plot
```{r}
#filter for just temp data

sal.dat <- filter(dat.grouped, WQ.type == "sal.psu")


#plot mean temp per day by date
sal_plot <- sal.dat %>%
  ggplot(aes(x=date, y=mean, color = tank))+
  geom_line() + 
  geom_point() +
  scale_x_date(date_breaks = "1 day", date_labels = "%m-%d") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90)) +
  ylab("Salinity (psu)")+
  xlab("Date");sal_plot

ggsave(filename="../figures/salinity.plot.pdf", plot=sal_plot, width=10, height=5, units="in")

```

#Light plot
```{r}
#filter for just temp data

light.dat <- filter(dat.grouped, WQ.type == "light")


#plot mean temp per day by date
light_plot <- light.dat %>%
  ggplot(aes(x=date, y=mean, color = tank))+
  geom_line() + 
  geom_point() +
  scale_x_date(date_breaks = "1 day", date_labels = "%m-%d") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90)) +
  ylab(expression(atop("Photon Flux Density", (mu*mol~photons~m^{-2}~s^{-1})))) +
  xlab("Date");light_plot

ggsave(filename="../figures/light.plot.pdf", plot=light_plot, width=10, height=5, units="in")

```

# Total alkalinity plot
```{r}
#filter for just temp data

TA.dat <- filter(dat.grouped, WQ.type == "TA")


#plot mean temp per day by date
TA_plot <- TA.dat %>%
  ggplot(aes(x=date, y=mean, color = tank))+
  geom_line() + 
  geom_point() +
  scale_x_date(date_breaks = "1 day", date_labels = "%m-%d") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90)) +
  ylab("Total Alkalinity") +
  xlab("Date");TA_plot

ggsave(filename="../figures/TA.plot.pdf", plot=TA_plot, width=10, height=5, units="in")



```

# calcium alkalinity plot
```{r}
#filter for just temp data

ca.dat <- filter(dat.grouped, WQ.type == "ca")


#plot mean temp per day by date
ca_plot <- ca.dat %>%
  ggplot(aes(x=date, y=mean, color = tank))+
  geom_line() + 
  geom_point() +
  scale_x_date(date_breaks = "1 day", date_labels = "%m-%d") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90)) +
  ylab("Calcium (Ca) (ppm)") +
  xlab("Date");ca_plot

ggsave(filename="../figures/ca.plot.pdf", plot=ca_plot, width=10, height=5, units="in")



```

# magnesium plot
```{r}
#filter for just temp data

mg.dat <- filter(dat.grouped, WQ.type == "mg")


#plot mean temp per day by date
mg_plot <- mg.dat %>%
  ggplot(aes(x=date, y=mean, color = tank))+
  geom_line() + 
  geom_point() +
  scale_x_date(date_breaks = "1 day", date_labels = "%m-%d") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90)) +
  ylab("Magnesium (Mg) (ppm)") +
  xlab("Date");mg_plot

ggsave(filename="../figures/mg.plot.pdf", plot=mg_plot, width=10, height=5, units="in")



```


# carbonate alkalinity plot
```{r}
#filter for just temp data

alk.dat <- filter(dat.grouped, WQ.type == "alk")


#plot mean temp per day by date
alk_plot <- alk.dat %>%
  ggplot(aes(x=date, y=mean, color = tank))+
  geom_line() + 
  geom_point() +
  scale_x_date(date_breaks = "1 day", date_labels = "%m-%d") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90)) +
  ylab("Carbonate Alkalinity (dkh)") +
  xlab("Date");alk_plot

ggsave(filename="../figures/alk.plot.pdf", plot=alk_plot, width=10, height=5, units="in")



```

# pH plot
```{r}
#filter for just temp data

ph.dat <- filter(dat.grouped, WQ.type == "pH")


#plot mean temp per day by date
ph_plot <- ph.dat %>%
  ggplot(aes(x=date, y=mean, color = tank))+
  geom_line() + 
  geom_point() +
  scale_x_date(date_breaks = "1 day", date_labels = "%m-%d") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90)) +
  ylab("pH (mV)") +
  xlab("Date");ph_plot

ggsave(filename="../figures/ph.plot.pdf", plot=ph_plot, width=10, height=5, units="in")



```